services:
  - type: web
    name: expense-manager-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    region: oregon # or ohio, frankfurt, singapore
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET_NAME
        value: expense-tracker-prod1
      - key: AWS_SES_FROM_EMAIL
        value: expense@alpha-devs.cloud
      - key: REVENUECAT_SECRET_API_KEY
        sync: false
      - key: REVENUECAT_ENTITLEMENT_ID
        value: Expense Tracker Pro
